version: '1.0'

services:
  mailagent:
    container_name: mailagent
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    networks:
      - mail_network
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail-server
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      # - ./docker-data/nginx-proxy/certs/:/usr/local/psa/var/modules/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      # - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
      - LOG_LEVEL=debug
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - mail_network

networks:
  mail_network:
    driver: bridge
